### ISSUE TITLE
Node.js server CRL issue

### ISSUE THREAD

**Issue by eflumerf** [art-daq/artdaq_utilities#90]
*This issue has been migrated from https://cdcvs.fnal.gov/redmine/issues/23440 (FNAL account required)*
*Originally created by @eflumerf on 2019-10-18 16:18:41*

----

From: Gennadiy A. Lukhanin <glukhanin@solitonica.com> 
Sent: Friday, October 18, 2019 11:09 AM
To: Eric Flumerfelt <eflumerf@fnal.gov>
Subject: node server and CLR
 
Hi Eric, I've installed the latest version of node_server on icarus-db01 and had to comment out the HTTPS server due to the following error. 
 
Error: Failed to parse CRL
    at Object.createSecureContext (_tls_common.js:157:19)
    at Server (_tls_wrap.js:868:27)
    at new Server (https.js:62:14)
    at Object.createServer (https.js:85:10)
    at Object.<anonymous> (/data/artdaq_database/products/artdaq_node_server/v1_01_06a/serverbase.js:538:24)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
_tls_common.js:157
        c.context.addCRL(options.crl[i]);
                  ^
 
 
I also tried downloading certificates by hand and that did not work, any thoughts? 
 
[artdaq@icarus-db01 artdaq_database]$ ll /data/artdaq_database/icarus_v4x_db/webconfigeditor/certificates/
total 8
-rw-r--r-- 1 artdaq P-1052 456 Oct 17 04:01 cilogon-basic.crl
-rw-r--r-- 1 artdaq P-1052 666 Oct 17 04:01 cilogon-basic.r0
 
Thank you, g

**Comment by eflumerf** [comment]
*Comment by @eflumerf on 2019-10-18 17:28:02*

----

Resolved by commit:node-server|81b141dd96d55167e40e9d5fef3c10f35ea1c562 and commit:node-server|30f8bcf9128975ed65ce0fdeebe729814a560cf9.
